# Site settings
name: Magda and Anders' Wedding
description: "Magda and Anders\' Wedding"

baseurl: '' # the subpath of your site, e.g. /blog
url: 'http://magdaandanders.com' # the base hostname & protocol for your site

# Build settings
markdown:            kramdown
relative_permalinks: false
permalink:           :title/

sass:
    sass_dir: _sass
    style:    compressed

gems:
    - jekyll-sitemap
    - jekyll-redirect-from
